### PR TITLE
Allie's Marketplace

### PR DESCRIPTION
**Pull request by doulos819**
### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).

This project is a simple one. We hope to use Mintbase as a suite of tools to support us in our goal to create a platform that is simple for creators to derive value from. Specifically, we hope to focus on creators that have specific needs when it comes to the sensitivity of their data (keeping it private, gated, or having the ability to delete their data at any time). While Mintbase currently offers a wonderful set of tools for the base layer of our project, we hope to build tools that can be used directly by creators to leverage Mintbase for their own unique goals.

For this specific grant proposal, we just want to get started making a useful platform for one such creator  [Allie Eve Knox](https://twitter.com/allieeveknox). As we build out her "Wishlist", we hope to also be building out tools and flows that more creators will find value in. The goal is that at the end of this first milestone, we will have provided at least one creator with a useful way to build their business on top of NEAR/Mintbase. As the project grows and we hit further milestones, we hope to generalize these tools/flows into a factory contract creator marketplace that allows creators to easily spin up a suite of contracts that suit their personal needs. 

> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.

### For which grant [level](https://github.com/Mintbase/Grants-Program#level_slider-levels) are you applying? 
- [x] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals and one pitch to Mintbase Council
- [ ] **Level 3**:  Unlimited, 5 approvals and mutliple pitches to Mintbase Council

### Application Checklist

- [x] The [application template](https://github.com/Mintbase/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] NEAR address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/Mintbase/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### How Did You Hear About our grants program?

- [ ] Mintbase Website
- [ ] Mintbase Community (Twitter, Discord, Telegram etc.)
- [ ] Hackathon
- [x] Personal Recommendation
- [ ] Investor/VC
- [ ] Online Search 
- [ ] Other: _______

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1203122172236847

### CODE REVIEW

**Review by nategeier — APPROVED** [review]
Excited to help pioneer NSFW content in a decentralized way.

**Review by mariamneu — APPROVED** [review]
congratulations!

**Review by kuvekep14 — APPROVED** [review]
Facilitate individuals creating standalone marketplace to make them more resilient from centralized threats

**Review by reginamintbase — APPROVED** [review]

**Review by mariamneu — APPROVED** [review]
Congrats :)

**Pull request merged**
