### PR TITLE
PWX submission

### PR DESCRIPTION
**Pull request by alfmatos**
### Project Abstract

We provide the means for Blenders (whisky producers) to connect to the global market by tokenizing Whisky Casks (where whisky matures) and trading them on the Portuguese Wine Exchange (PWX). We unlock access to Casks through NFTs  and through tokens, allowing early adopters to acquire great experiences and great prices while financing the whisky producing process. 

NFTs and Tokens are bound to the cask through smart contracts, and can be transformed into whisky or sold on the exchage for fun and profit, as Whisky is a great investment with historically a great ROI.

### For which grant [level](https://github.com/Mintbase/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals and one pitch to Mintbase Council
- [ ] **Level 3**:  Unlimited, 5 approvals and mutliple pitches to Mintbase Council

### Application Checklist

- [x] The [application template](https://github.com/Mintbase/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] NEAR address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/Mintbase/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### How Did You Hear About our grants program?

- [ ] Mintbase Website
- [x] Mintbase Community (Twitter, Discord, Telegram etc.)
- [ ] Hackathon
- [x] Personal Recommendation
- [ ] Investor/VC
- [ ] Online Search 
- [ ] Other: _______

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1203193854175034

### CODE REVIEW

**Comment by GodAK3** [comment]
*Project Abstract*



          New wisdom agency production is a startup company dedicated to
Raising mental health awareness through its brand. New wisdom agency's
production goals are to simply give minorities and unfortunate low-income
communities a fighting chance by providing a safe environment conducive to
growth and producing results. The mission is to help people understand
themselves more and learn how to learn more frequently through an
NFT-designed infrastructure. I believe NFT’s Viewed as the start of a
resource base economic system that will completely change the world and
every single being's way of living. The project goal is to create a
lifestyle movement with NFTs that will spark a revolution in every single
conscious being's mindset to learn how they can position themselves and
their family to create wealth. To achieve this, I must become a living
breathing first Human to BE an NFT and Change the worldview concept of it.

       Project 132 Soul Kingdom customs are my life work of artwork and
designs made into physical NTFS directly showing how NFTs can be both an
influential physical and digital asset. Most traditional people only view
NFTs as eye candy trophy digital assets limiting their view to investing in
the potential idea Which could help make a priceless fortune. How can we
change the meaning behind NTFS Forever? This answer is very simple give
NFTS 5 subcategories and constantly educate the masses on a platform simply
design to help Produce abundant prosperous results. Introducing the first
ever emotional in NFT debit/credit accompanied gift card with features like
mood capability, total security trackers, key pinpoints, business growth
marketing templates, and a gated Community entry key protection.
Introducing the world to NFT5 With influencers who are living testimonies
of the vision. My new number 754-802-9450 please contact me

THE  New Definition Of NFT5

-Never-ending Funds of Trust

-New Foundation of Thoughts

-Necessary Fair fitness Technique trainers

-Nanos Family's Teaching

-Non-Fundable Token.




*For which grant **level
<https://github.com/Mintbase/Grants-Program#level_slider-levels>** are you
applying?*

·  *Level 3*: Unlimited, 5 approvals and multiple pitches to Mintbase
Council

*Application Checklist*

*Mint-base Grant Proposal*



   - *Project Name:* New Wisdom APC
   - *Team Name:* Ysaac Saintil
   - *Payment Address:*
   https://wallet.near.org/recover-with-link/kingace132.near/clock%20hill%20bid%20live%20sweet%20trick%20obtain%20gravity%20spell%20weasel%20come%20ecology
   - EASTERN BANK
   - Checking#406799477
   - Routing#011301798
   - *Level*
   <https://github.com/Mintbase/Grants-Program/blob/main/README.md#level_slider-levels>
   *:* 3

[image: ⚠️] *The combination of your GitHub account submitting the
application and the payment address above will be your unique identifier
during the program. Please keep them safe.*



*Project Overview *[image: 📄]



Creating the first-ever digital conventional supermarket. Ending world
inequality. Show the world we can change and grow. I am hereby
offering  Near protocol  75% ownership of new wisdom APC.



*Overview*

*I Need help raising $80,000,000 *

Please provide the following: true  Partnership



   - Sole king custom LLC, Sole kingdom INC, We are here to Support you Inc
   - It’s okay to be different, Being the change  in the world you want to
   see
   - My project is 100% related to integrating into the Mint-base / NEAR
   ecosystem.
   - It’s me only, For now, I have gone homeless trying to tell friends and
   family about the blockchain world and to change the way they think.



*Project Details*

Yes, let us create an App called Inner-Connected {IC}.ITS features will be
letting the public see Big businesses connections and Communicate about
news, and NFT PURCHASES. And more The app’s sole user purpose is only for
positive thinkers, and entrepreneurs like myself. All users will receive
free NFTS, and near every time they log on. This app will also be used so
people can book me for custom sneakers and Apparel. For every 10,000 NFT
and custom sold let us create the First ever Mint-base library/museum that
tourists come to see all around the world.



   - I created the first-ever Nike Custom  market merge NFT
   - I Need A Bigger Team, And a user interface
   - I need a cyber security team, and funding
   - Market research and Affordable Patent attorney
   - My  project is *not*  a scam and will not  provide or implement fraud
   or break the law
      - I am expecting to create quadrillion dollars in business value in 5
      years expectation and impact 100 million families in 5 years. Nothing can
      stop us.



*Ecosystem Fit*

Help us locate your project in the Mint-base landscape and what problems it
tries to solve by answering each of these questions:



   - Where and how does your project fit into the ecosystem?



I'm 22 years old, have been sleeping in a car for 3 months, I haven't
showered for 3 months.I have lost a sense of touch with my humanity. I just
want the credit for my work before I die. My passion has always been to be
an artist, and inventor, I create Nft, produce and solve problems. My
project fits in the near and mint base ecosystem because I want to end
poverty with my story and life work in art.



   - Who is your target audience (parachain/dapp/wallet/UI developers,
   designers, your own user base, some dapp's userbase, yourself)?



My target audience is everyone but Mostly the designer and fashion Agency.
The goal is to hit the world like a category 5 Hurricane that everyone will
never stop talking about.



   - What is need(s) does your project meet?



I need funding, a full review, and a team that is fearless and the best at
their role.



   - Are there any other projects similar to yours in the Mint-base / NEAR
   ecosystem?



No, I am the original and the world’s greatest.



   - If so, how is your project different?



My project is different and creative because of my story and I put my life
into this. My pain and the current situation I faced for this. no one in my
family likes me for thinking like this.



   - If not, are there similar projects in related ecosystems?

I have created the one and only.



*Team *[image: 👥]



*Team members*

   - Ysaac Saintil, Cameron Dennis



   - This is the name of a list of people I want on my team when I am
   funded if they accept our offer. {Eden.S, Abraham.S, Jack.S, Jamel. H,
   Brandon. P, Francis. V, Stevenley. A Rebecca.s, Caly.s, Christopher
   D, Shaniya .J, Marcus & Karl, Genesis.M, And Calbe.s



My story



*Contact*

   - *Contact Name:* Ysaac Saintil
   - *Contact Email:* ***@***.***
   - *NUMBER:620-705-1899 OR 754-802-9450*



*Legal Structure*

   - *Registered Address:* 13250 Ne 5th Ave ,North Miami,33161
   - *Registered Legal Entity:* New wisdom Agency Production Crop



*Team's experience*

I once designed a sneaker and sold it for $750. I  have studied and read
books all about marketing  I have incredible marketing ideas but it will
require funding.





*Development Status *[image: 📖]

https://youtu.be/CFvWRgUFn9U



https://youtu.be/wa7yPf8YNWs



* Add a lit (1).pptx
<https://drive.google.com/file/d/11uRrODPEaCn4FW9IUFpTZG2PR3WKQL-x/view?usp=drive_web>*





* new Wisdom aGENCY PRODUCTION COR.pdf
<https://drive.google.com/file/d/1ej9Yb5O_JzEvZuW0WuUPywlNq8uweIHb/view?usp=drive_web>*



https://www.mintbase.io/thing/h8Bb5BoJF4ZKrms9F_8nbhfInosZmUPgi7C90Hkq6mo:kingace132.mintbase1.near



https://www.mintbase.io/thing/hAXu0S5itqFd09jpIOBme6tVN0D-I2_38rtyPpzTsac:kingace132.mintbase1.near



https://www.mintbase.io/thing/l821RFMtZnuPYlQDVXABm7IA_jjfwbti31_EnTFRUYE:kingace132.mintbase1.near



https://www.mintbase.io/thing/nOLX3_uAWlSBio-SyCbO4yjggW0hxkRLb8Rln-vAz1k:kingace132.mintbase1.near



https://www.mintbase.io/thing/h8Bb5BoJF4ZKrms9F_8nbhfInosZmUPgi7C90Hkq6mo:kingace132.mintbase1.near



If you've already started implementing your project or it is part of a
larger repository, please provide a link and a description of the code
here. In any case, please provide some documentation on the research and
other work you have conducted before applying. This could be:

   - links to improvement proposals or RFPs
   <https://github.com/mintbase/Grants-Program/tree/master/rfp-proposal>
(requests
   for proposal),
   - academic publications relevant to the problem,
   - links to your research diary, blog posts, articles, forum discussions
   or open GitHub issues,
   - references to conversations you might have had related to this project
   with anyone from the Mintbase Foundation,
   - previous interface iterations, such as mock-ups and wireframes.



*Development Roadmap *[image: 🔩]

*Step1:  Fund me, and own 75 % of my company*

*Step2.  Let’s do a full overview of my hand-painted custom Nike designs*

*Step3. Let’s create 10 custom NIKE MARKET MERGES  NFT*

*Step 4.  market and built attention around them*

*Step5 . sell the designs to Nike and apple for 100million each.*

*Step 6. Then sell Nike a shoe design invention for another $100MILLION*

*Step7.  Help me build a team of powerful individuals who love their
roles.Then create The first NFT movie.*

*Step8: CREATE an app that makes Us 800 million in business one year*

*Step 9 .have near and Mint-base NFT THE FACE  OF WORLDS LEADING
CRYPTOCURRENCY AND Technology.*

*Step 10. have over 200 near and mint base plazas and malls all around the
world in 3 years*



*Overview*

   - *Total Estimated Duration:* Duration of the whole project (5YEARS)
   - *Full-Time Equivalent (FTE):* 75 WORKERS,WORKING 40 HOURS Average
   WEEKLY of full-time employees working on the project FOR 3 YEARS
   - *Total Costs:* Requested amount in USD for the whole project
   ($900,000).



   - *Milestone 1 Example — Mintbase Marketing Modules*
   - *Estimated duration:* 5 years
   - *FTE:* 156,000 hours
   - *Costs:* 180,000,000USD

*Number*

*Deliverable*

*Specification*

0a.

License

 LOCATED AT BOTTOM

0b.

Documentation

provided at the bottom. both online offline events,* documentation* of
business paperwork basic *tutorial* that explains how a user signs up for
one of our Mintbase NFT for purchase.

0c.

Teaching Guide

hop on a call zoom or youtube call daily Mon-Fri explaining the opportunity
and answer questions.

0d.

Marketing attraction

We will provide ntf custom sneaker and apparel giveaways via Instagram live
giveaways.

0e.

Article and blog post

We will publish a blogging *article*/workshop that explains how millions of
jobs will be made in the near protocol/mint-base blockchain technology.

1.

Mintbase module: soul kingdom custom

We will create a Mintbase / NEAR module that will custom put in a custom
sneaker or appeal orders

2.

Mintbase module: New wisdom APC

We will create a Mintbase / NEAR module that will HOW PEOPLE HOW EMPOWER
THEIR SELF THUR HARD TIMES.

3.

Mintbase module: Weheatosupportyou

We will create a Mintbase / NEAR module that will teach people how to up
with their body and mindset .

4.

NEAR NWAPC POINTS AND COINS

NWAPC membership website will cause our custom chain will interact in such
a way it delivers more traffic to the mint base/near space attracting more
intelligence loyal users.

*Milestone 2 Example — NFTs portrait canvas*

   - *Estimated Duration:* 1 month
   - *FTE:* 1
   - *Costs:* 50,000 USD

…50-100 hand paint canvas of different large companies logo then take
pictures of then sell them as NFT AND CANVAS TOO .



*Future Plans*

Make History, buy Property, built the first cryptocurrency city and public
museum

Using social media, and finding ways to die a legend .Create one of the
world most powerful social media production companies.



   - I intend to use social media and network marketing, enhance level of
   action of making people aware of blockchain and the new digital era .My
   promotion will come  from my story  and my project will be supported in
   short term because my passion for art and business will allow me to create
   an athenthenic story on why my NFT are the different, and im highly
   motivated to do the job.





   - My  long-term plans and intentions in relation to this prove all my
   friends and family wrong and show them I’m not crazy for believing in my
   artwork and designs. I want in 5 years to work so hard I can live a better
   life then sleeping in a car for 6months and cry of hungry for 10days
   because im waiting on $200 in food stamps every month. I want to travel the
   world with good friends and take pictures everyday.



*Additional Information *[image: ➕]

*How did you hear about the Grants Program?*

Personal recommendation



Here you can also add any additional information that you think is relevant
to this application but isn't part of it already, such as:

   - Work you have already done.
   - If there are any other teams who have already contributed
   (financially) to the project.
   - Previous grants you may have applied for.

*15 Attachments*





Preview YouTube video MY NFT INVENTIONS Complete project idea to roadmap ()
<https://www.youtube.com/watch?v=CFvWRgUFn9U&authuser=1>

[image: Text Description automatically generated]
<https://www.youtube.com/watch?v=CFvWRgUFn9U&authuser=1>

<https://www.youtube.com/watch?v=CFvWRgUFn9U&authuser=1>

*MY NFT INVENTIONS Complete project idea to roadmap ()
<https://www.youtube.com/watch?v=CFvWRgUFn9U&authuser=1>*

Preview YouTube video New Wisdom Agency Production Corporation (OFFICIAL)
Presentation for Mintbase Grants Program 6/7/22
<https://www.youtube.com/watch?v=wa7yPf8YNWs&authuser=1>

[image: Text Description automatically generated]
<https://www.youtube.com/watch?v=wa7yPf8YNWs&authuser=1>

<https://www.youtube.com/watch?v=wa7yPf8YNWs&authuser=1>

*New Wisdom Agency Production Corporation (OFFICIAL) Presentation for
Mintbase Grants Program 6/7/22
<https://www.youtube.com/watch?v=wa7yPf8YNWs&authuser=1>*



*4 Attachments* • Scanned by Gmail



Preview YouTube video MY NFT INVENTIONS Complete project idea to roadmap ()
<https://www.youtube.com/watch?v=CFvWRgUFn9U&authuser=1>

[image: Text Description automatically generated]
<https://www.youtube.com/watch?v=CFvWRgUFn9U&authuser=1>

<https://www.youtube.com/watch?v=CFvWRgUFn9U&authuser=1>

*MY NFT INVENTIONS Complete project idea to roadmap ()
<https://www.youtube.com/watch?v=CFvWRgUFn9U&authuser=1>*

Preview YouTube video New Wisdom Agency Production Corporation (OFFICIAL)
Presentation for Mintbase Grants Program 6/7/22
<https://www.youtube.com/watch?v=wa7yPf8YNWs&authuser=1>

[image: Text Description automatically generated]
<https://www.youtube.com/watch?v=wa7yPf8YNWs&authuser=1>

<https://www.youtube.com/watch?v=wa7yPf8YNWs&authuser=1>

*New Wisdom Agency Production Corporation (OFFICIAL) Presentation for
Mintbase Grants Program 6/7/22
<https://www.youtube.com/watch?v=wa7yPf8YNWs&authuser=1>*







·  *How Did You Hear About our grants program?*





·  Personal Recommendation- Cameron Dennis
·
------------------------------

*You can view, comment on, or merge this pull request online at:*

  https://github.com/Mintbase/Grants-Program/pull/55

*Commit Summary*

· 4b5ccf9
<https://github.com/Mintbase/Grants-Program/pull/55/commits/4b5ccf9c91f711c61a47d2104669b7369947d38a>
PWX submission

*File Changes*

*Patch Links:*

https://github.com/Mintbase/Grants-Program/pull/6

**Comment by GodAK3** [comment]
Hello I submitted a pull request application for mostly a partnership I
simply needed a grant to get ball rolling and finding a place to create an
better environment to express my interest in creating a physical NFTs and
digital NFT ! I really didn’t understand the site in which I submitted the
application on! I am still wondering was my application ever viewed!
Please let me know!  I look forward to hearing from  this
amazing opportunity . Please don’t hesitate to give me a call on any
updates on my application or what was thought of my proposal application I
 am simply  looking forward to walk in my purposes bye creating an company
based on my passion for art , and Impacting lives with my Art of Marketing
a different type of NFTs!

**Comment by GodAK3** [comment]
Please  call me as soon as possible at 7548029450

**Review by reginamintbase — APPROVED** [review]
Parabéns!

**Review by kuvekep14 — APPROVED** [review]

**Pull request merged**
