### PR TITLE
AMBER Playable NFT Marketplace based on Mintbase technology.

### PR DESCRIPTION
**Pull request by andreykobal**
### Project Abstract

AMBER Playable NFT Marketplace based on Mintbase technology.

Our proposal is to develop a Playable NFT Marketplace Based on AMBER Open-source Metaverse, which will be the Playable NFT Marketplace powered by Mintbase technology with virtual asseet ownership confirmation and in-game NFT utility. 

### For which grant [level](https://github.com/Mintbase/Grants-Program#level_slider-levels) are you applying? 
- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 5 approvals (for > $100k Mintbase Council approval)

### Application Checklist

- [x] The [application template](https://github.com/Mintbase/Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] NEAR address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledged the [terms and conditions](https://github.com/Mintbase/Grants-Program/blob/master/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery#process).

### How Did You Hear About our grants program?

- [x] Mintbase Website
- [x] Mintbase Community (Twitter, Discord, Telegram etc.)
- [ ] Hackathon
- [x] Personal Recommendation
- [ ] Investor/VC
- [ ] Online Search 
- [ ] Other: _______

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1202786300732609

### CODE REVIEW

**Comment by reginamintbase** [comment]
Gm!

Thank you for submitting your project to the Mintbase Grants Program.

We're starting to review applications now and will be in touch over email moving forward. Please do drop your contact here in the comments or reach out to us at grants@mintbase.io. Feel free to add any extra information you'd like us to consider.

Looking forward to working together! Let's get building :)

**Comment by andreykobal** [comment]
Hi @reginamintbase , thanks for your reply! 

Let's continue communicating on telegram, feel free to text me (https://t.me/andrey10010)
) or Valentin (https://t.me/INF_INI_TY)

Kind regards, 
Andreas

**Comment by andreykobal** [comment]
Updates to the grant proposal in the [last commit](https://github.com/Mintbase/Grants-Program/pull/16/commits/6c76fa75d9dffd99c3896cc6acdbf4e204e3378e) to fit within the budget proposed by the Mintbase team

**Review by nategeier — APPROVED** [review]
Let's go! Interoperable gaming markets, here we come!

**Review by mariamneu — APPROVED** [review]
Congratulations!

**Review by reginamintbase — APPROVED** [review]

**Pull request merged**
